# This workflow checks out code, builds an image, performs a container image
# vulnerability scan with Anchore's Grype tool, and integrates the results with GitHub Advanced Security
# code scanning feature.  For more information on the Anchore scan action usage
# and parameters, see https://github.com/anchore/scan-action. For more
# information on Anchore's container image scanning tool Grype, see
# https://github.com/anchore/grype
name: Anchore Enterprise Test

on:
#  push:
#    branches:
#      - master
#  schedule:
#    - cron: '38 19 * * 6'
  workflow_dispatch:
    branches:
      - master
      
jobs:
  Build-Push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and Push the Docker image
      run: |
        docker build . --file Dockerfile --tag ${GITHUB_REPOSITORY}:${GITHUB_SHA}
        docker push ${GITHUB_REPOSITORY}:${GITHUB_SHA}

  Enterprise-Queue:
    runs-on: ubuntu-latest
    steps:
    - name: Add to Enterprise Queue
      env: 
        ANCHORE_CLI_PASS: ${{ secrets.ANCHORE_PASS }}
        ANCHORE_CLI_USER: ${{ secrets.ANCHORE_USER }}
        ANCHORE_CLI_URL: ${{ secrets.ANCHORE_URL }}
      run: docker run -e ANCHORE_CLI_USER -e ANCHORE_CLI_PASS -e ANCHORE_CLI_URL anchore/engine-cli anchore-cli image add ${GITHUB_REPOSITORY}:${GITHUB_SHA}

#      run: docker run anchore/engine-cli anchore-cli --u ${ANCHORE_CLI_USER} --p ${ANCHORE_CLI_PASS} --url ${ANCHORE_CLI_URL} image add ${GITHUB_REPOSITORY}:${GITHUB_SHA}

# login to ghcr.io
#      - name: Log in to the Container registry
#        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}

# push to scratch repo?   
#    - name: Run a container command
#      run: docker run anchore/engine-cli anchore-cli --u myuser --p mypw --url http://127.0.0.1:8228/v1 system status
# anchore-cli image add
# image wait
# evaluate check?
      
#    - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
#      uses: anchore/scan-action@main
#      with:
#        image: "${GITHUB_REPOSITORY}:${GITHUB_SHA}"
#        fail-build: false
#        acs-report-enable: true
#    - name: Upload Anchore Scan Report
#      uses: github/codeql-action/upload-sarif@v1
#      with:
#        sarif_file: results.sarif
